apiVersion: v1
kind: Pod
metadata:
   name: App
   labels:
     name: App
spec:
   containers:
   - name : nginx
     image: $img
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: App
spec:
  selector:
    name: App
  ports:
    - port: 80
  type: LoadBalancer