apiVersion: v1
kind: Pod
metadata:
   name: app-$env
   labels:
     name: app-$env
spec:
   containers:
   - name : nginx-$env
     image: $img
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-$env
spec:
  selector:
    name: app-$env
  ports:
    - port: 80
  type: LoadBalancer